import XCTest
@testable import WellnessCore

final class WellnessCoreTests: XCTestCase {
    func testUnitRoundTrips() { XCTAssertEqual(Units.pounds(fromKilograms: Units.kilograms(fromPounds: 150)), 150, accuracy: 0.0001); XCTAssertEqual(Units.fluidOunces(fromLiters: Units.liters(fromFluidOunces: 64)), 64, accuracy: 0.0001); XCTAssertEqual(Units.miles(fromKilometers: Units.kilometers(fromMiles: 3.1)), 3.1, accuracy: 0.0001) }
    func testGoalCalculation() { let result = GoalCalculator.recommend(age: 30, sex: .female, heightCM: 165, weightKG: 70, activity: .moderate, mode: .cut); XCTAssertGreaterThan(result.calories, 1_199); XCTAssertGreaterThan(result.proteinGrams, 100) }
    func testActiveCaloriesNeverIncreaseTarget() { XCTAssertEqual(GoalCalculator.target(base: 1800, workoutOverride: nil, restOverride: nil, isWorkoutDay: true, activeCalories: 0), GoalCalculator.target(base: 1800, workoutOverride: nil, restOverride: nil, isWorkoutDay: true, activeCalories: 1_200)) }
    func testWorkoutAndRestOverrides() { XCTAssertEqual(GoalCalculator.target(base: 1800, workoutOverride: 1900, restOverride: 1700, isWorkoutDay: true, activeCalories: 500), 1900); XCTAssertEqual(GoalCalculator.target(base: 1800, workoutOverride: 1900, restOverride: 1700, isWorkoutDay: false, activeCalories: 0), 1700) }
    func testFoodWeightMacros() { let food = FoodSnapshot(name: "Chicken", nutrientsPer100Grams: .init(calories: 165, protein: 31, carbs: 0, fat: 3.6)); let value = food.nutrients(grams: 165); XCTAssertEqual(value.calories, 272.25, accuracy: 0.001); XCTAssertEqual(value.protein, 51.15, accuracy: 0.001) }
    func testSavedMealTotals() { let a = FoodLog(date: .now, meal: .breakfast, foodName: "A", amountGrams: 1, snapshot: .init(calories: 100, protein: 10)); let meal = SavedMeal(name: "Breakfast", items: [a,a]); XCTAssertEqual(meal.totals.calories, 200); XCTAssertEqual(meal.totals.protein, 20) }
    func testDailyAndWeeklyCompletion() { let complete = CompletionInput(workout: true, calories: 1800, calorieTarget: 1800, protein: 120, proteinTarget: 120, steps: 10_000, stepTarget: 10_000, waterLiters: 2, waterTargetLiters: 2, supplementFraction: 1); XCTAssertEqual(CompletionCalculator.score(complete), 1, accuracy: 0.0001); XCTAssertEqual(CompletionCalculator.weekly([complete, complete]), 1) }
    func testTemplateSessionIsImmutableValueSnapshot() { var template = WorkoutTemplateValue(name: "Lower", exercises: [.init(exerciseName: "Squat", sets: [.init(weightKG: 50, reps: 8)])]); let session = template.session(on: .now); template.exercises[0].sets[0].reps = 12; XCTAssertEqual(session.exercises[0].sets[0].reps, 8) }
    func testSevenDayAverage() { let cal = Calendar(identifier: .gregorian); let today = Date(timeIntervalSince1970: 1_700_000_000); let points = (0..<7).map { WeightPoint(date: cal.date(byAdding: .day, value: -$0, to: today)!, kilograms: Double(70 + $0)) }; XCTAssertEqual(Trends.sevenDayAverage(points, through: today, calendar: cal)!, 73, accuracy: 0.001) }
    func testMockServicesAndDemoIsolation() async throws { let health: HealthProviding = MockHealth(); let snapshot = try await health.snapshot(for: .now); XCTAssertEqual(snapshot.steps, 8_000); let nutrition: NutritionProvider = MockNutrition(); let foods = try await nutrition.search("banana"); XCTAssertEqual(foods.first?.name, "Banana"); let real = [1,2]; var demo = real; demo.append(3); XCTAssertEqual(real, [1,2]) }
}
private struct MockHealth: HealthProviding { func authorize() async throws {} ; func snapshot(for date: Date) async throws -> HealthSnapshot { .init(steps: 8_000, activeCalories: 350) } }
private struct MockNutrition: NutritionProvider { func search(_ query: String) async throws -> [FoodSnapshot] { [.init(name: "Banana", nutrientsPer100Grams: .init(calories: 89))] }; func barcode(_ code: String) async throws -> FoodSnapshot? { nil } }
