import SwiftUI
import SwiftData
import Charts
import PhotosUI
import UIKit

struct CalendarHistoryView: View {
    let profile: AppProfile; @State private var month = Date.now; @Query private var workouts:[WorkoutEntity]; @Query private var logs:[FoodLogEntity]; @Query private var waters:[WaterEntity]; @Query private var activities:[ActivityEntity]
    private let columns = Array(repeating: GridItem(.flexible()), count: 7)
    var body: some View { ScrollView { VStack(spacing:18) { EditorialTitle(eyebrow:"History", title:month.formatted(.dateTime.month(.wide).year())); HStack { Button { month = Calendar.current.date(byAdding:.month,value:-1,to:month)! } label:{Image(systemName:"chevron.left")}; Spacer(); Button("Today"){month = .now}; Spacer(); Button { month = Calendar.current.date(byAdding:.month,value:1,to:month)! } label:{Image(systemName:"chevron.right")} }; LazyVGrid(columns:columns,spacing:12){ ForEach(Calendar.current.veryShortWeekdaySymbols,id:\.self){Text($0).font(.caption).foregroundStyle(.secondary)}; ForEach(days(),id:\.self){date in NavigationLink { DayDetailView(date:date, profile:profile) } label:{ VStack { Text("\(Calendar.current.component(.day,from:date))"); ZStack { Circle().stroke(.secondary.opacity(0.15),lineWidth:3); Circle().trim(from:0,to:score(date)).stroke(.sage,lineWidth:3).rotationEffect(.degrees(-90)) }.frame(width:25,height:25) }.frame(height:55) }.buttonStyle(.plain) } } }.padding() }.navigationTitle("Calendar").navigationBarTitleDisplayMode(.inline) }
    private func days()->[Date]{ let cal=Calendar.current, interval=cal.dateInterval(of:.month,for:month)!; let range=cal.range(of:.day,in:.month,for:month)!; let firstWeekday=cal.component(.weekday,from:interval.start); let prefix=firstWeekday-cal.firstWeekday >= 0 ? firstWeekday-cal.firstWeekday : firstWeekday-cal.firstWeekday+7; return (0..<(prefix+range.count)).compactMap { cal.date(byAdding:.day,value:$0-prefix,to:interval.start) } }
    private func score(_ date:Date)->Double { let cal=Calendar.current; let m=logs.filter{cal.isDate($0.date,inSameDayAs:date)}; let macro=m.reduce(Macro()){ $0 + .init(calories:$1.calories,protein:$1.protein,carbs:$1.carbs,fat:$1.fat)}; return CompletionCalculator.score(.init(workout:workouts.contains{cal.isDate($0.date,inSameDayAs:date)&&$0.completed},calories:macro.calories,calorieTarget:Double(profile.calorieTarget),protein:macro.protein,proteinTarget:Double(profile.proteinTarget),steps:activities.first{cal.isDate($0.date,inSameDayAs:date)}?.steps ?? 0,stepTarget:Double(profile.stepTarget),waterLiters:waters.filter{cal.isDate($0.date,inSameDayAs:date)}.map(\.liters).reduce(0,+),waterTargetLiters:profile.waterTargetLiters,supplementFraction:0)) }
}

struct DayDetailView: View { let date:Date; let profile:AppProfile; @Query private var workouts:[WorkoutEntity]; @Query private var logs:[FoodLogEntity]; @Query private var waters:[WaterEntity]; @Query private var weights:[WeightEntity]; @Query private var activities:[ActivityEntity]; @State private var food=false; @State private var weight=false
    var body:some View { let cal=Calendar.current; let dayWorkouts=workouts.filter{cal.isDate($0.date,inSameDayAs:date)}; let dayLogs=logs.filter{cal.isDate($0.date,inSameDayAs:date)}; List { Section("Workout"){if dayWorkouts.isEmpty{Text("No workout logged").foregroundStyle(.secondary)};ForEach(dayWorkouts){w in NavigationLink(w.name){w.isCardio ? AnyView(CardioEditor(workout:w)):AnyView(StrengthSessionView(workout:w))}}}
        Section("Nutrition"){ForEach(dayLogs){entry in HStack{Text(entry.foodName);Spacer();Text("\(Int(entry.calories)) kcal")}};Button("Add forgotten food"){food=true}}
        Section("Activity"){let a=activities.first{cal.isDate($0.date,inSameDayAs:date)};LabeledContent("Steps",value:"\(Int(a?.steps ?? 0))");LabeledContent("Active calories",value:"\(Int(a?.activeCalories ?? 0)) kcal");LabeledContent("Water",value:"\(Int(waters.filter{cal.isDate($0.date,inSameDayAs:date)}.map(\.liters).reduce(0,+)*1000)) mL")}
        Section("Weight"){if let w=weights.first(where:{cal.isDate($0.date,inSameDayAs:date)}){Text("\(w.kilograms,format:.number.precision(.fractionLength(1))) kg")};Button("Add or update weight"){weight=true}} }.navigationTitle(date.formatted(date:.abbreviated,time:.omitted)).sheet(isPresented:$food){NavigationStack{AddFoodView(date:date)}}.sheet(isPresented:$weight){WeightEntryView(profile:profile,date:date)} }
}

struct ProgressTabView: View { let profile:AppProfile; @Query(sort:\WeightEntity.date) private var weights:[WeightEntity]; @Query(sort:\PhotoSetEntity.date,order:.reverse) private var photos:[PhotoSetEntity]; @State private var addPhoto=false; @State private var compare=false
    var body:some View { ScrollView { VStack(spacing:18){EditorialTitle(eyebrow:"Progress",title:"The long view"); WellnessCard { Text("Goal").font(.headline); if let latest=weights.last { Text("\(display(latest.kilograms))  →  \(display(profile.goalKG))").font(.system(.title2,design:.serif)); if let avg=Trends.sevenDayAverage(weights.map{WeightPoint(date:$0.date,kilograms:$0.kilograms)},through:.now){Text("7-day average: \(display(avg))").foregroundStyle(.secondary)} } else { ContentUnavailableView("No weight history",systemImage:"scalemass",description:Text("Log a weight to begin your gentle trend.")) } }; if !weights.isEmpty { WellnessCard { Chart(weights){w in LineMark(x:.value("Date",w.date),y:.value("Weight",w.kilograms)).foregroundStyle(.sage);PointMark(x:.value("Date",w.date),y:.value("Weight",w.kilograms)).foregroundStyle(.sage)}.frame(height:190) } }; WellnessCard { Text("Progress photos").font(.headline); if photos.isEmpty { Text("Your photos remain in private app storage.").foregroundStyle(.secondary) } else { Text("Latest set: \(photos[0].date.formatted(date:.abbreviated,time:.omitted))") }; HStack{Button("Add this week"){addPhoto=true}.buttonStyle(.borderedProminent);Button("Compare"){compare=true}.disabled(photos.count<2).buttonStyle(.bordered)} } }.padding() }.background(Color.cream.opacity(0.45)).sheet(isPresented:$addPhoto){PhotoCaptureFlow()}.sheet(isPresented:$compare){PhotoCompareView(photos:photos)}.navigationTitle("Progress").navigationBarTitleDisplayMode(.inline) }
    private func display(_ kg:Double)->String {
        let value = profile.units == .imperial ? Units.pounds(fromKilograms: kg) : kg
        let unit = profile.units == .imperial ? "lb" : "kg"
        return value.formatted(.number.precision(.fractionLength(1))) + " " + unit
    }
}

struct WeightEntryView:View { @Environment(\.dismiss) private var dismiss;@Environment(\.modelContext) private var context;let profile:AppProfile;let date:Date;@State private var value=0.0;var body:some View{NavigationStack{Form{TextField(profile.units == .imperial ? "Weight (lb)":"Weight (kg)",value:$value,format:.number).keyboardType(.decimalPad);Button("Save"){let kg=profile.units == .imperial ? Units.kilograms(fromPounds:value):value;context.insert(WeightEntity(date:date,kilograms:kg));profile.currentKG=kg;try? context.save();dismiss()}}.navigationTitle("Log Weight").onAppear{value=profile.units == .imperial ? Units.pounds(fromKilograms:profile.currentKG):profile.currentKG}}} }

struct PhotoCaptureFlow:View { @Environment(\.dismiss) private var dismiss;@Environment(\.modelContext) private var context;@State private var selections:[PhotosPickerItem?]=[nil,nil,nil];@State private var paths=["","",""];let names=["Front","Side","Back"];var body:some View{NavigationStack{List{ForEach(0..<3,id:\.self){i in PhotosPicker(selection:Binding(get:{selections[i]},set:{selections[i]=$0;save($0,index:i)}),matching:.images){HStack{Image(systemName:paths[i].isEmpty ? "photo.badge.plus":"checkmark.circle.fill");Text(names[i]);Spacer();Text(paths[i].isEmpty ? "Choose":"Ready").foregroundStyle(.secondary)}}};Text("Images are copied to the app's private Documents directory and never uploaded.").font(.footnote).foregroundStyle(.secondary);Button("Save Photo Set"){guard paths.allSatisfy({!$0.isEmpty})else{return};context.insert(PhotoSetEntity(front:paths[0],side:paths[1],back:paths[2]));try? context.save();dismiss()}.disabled(paths.contains(""))}.navigationTitle("Weekly Photos")}};private func save(_ item:PhotosPickerItem?,index:Int){Task{guard let data=try? await item?.loadTransferable(type:Data.self)else{return};let url=FileManager.default.urls(for:.documentDirectory,in:.userDomainMask)[0].appendingPathComponent("progress-\(UUID()).jpg");try? data.write(to:url,options:.atomic);paths[index]=url.lastPathComponent}} }
struct PhotoCompareView:View { let photos:[PhotoSetEntity];@Environment(\.dismiss) private var dismiss;@State private var left=0;@State private var right=1;@State private var angle=0;var body:some View{NavigationStack{VStack{HStack{Picker("Earlier",selection:$left){ForEach(photos.indices,id:\.self){Text(photos[$0].date.formatted(date:.abbreviated,time:.omitted)).tag($0)}};Picker("Later",selection:$right){ForEach(photos.indices,id:\.self){Text(photos[$0].date.formatted(date:.abbreviated,time:.omitted)).tag($0)}}};Picker("Angle",selection:$angle){Text("Front").tag(0);Text("Side").tag(1);Text("Back").tag(2)}.pickerStyle(.segmented);HStack{photo(photos[left]);photo(photos[right])}.frame(maxHeight:.infinity)}.padding().navigationTitle("Compare").toolbar{Button("Done"){dismiss()}}}};private func photo(_ set:PhotoSetEntity)->some View{let path=[set.front,set.side,set.back][angle];let url=FileManager.default.urls(for:.documentDirectory,in:.userDomainMask)[0].appendingPathComponent(path);return Group{if let image=UIImage(contentsOfFile:url.path){Image(uiImage:image).resizable().scaledToFit()}else{RoundedRectangle(cornerRadius:18).fill(Color.sage.opacity(0.15)).overlay{Text(set.isDemo ? "Demo photo":"Photo unavailable")}}}.clipShape(RoundedRectangle(cornerRadius:18))} }

struct SettingsView:View { @Environment(\.dismiss) private var dismiss;@Environment(\.modelContext) private var context;let profile:AppProfile;@Query private var supplements:[SupplementEntity];@State private var newSupplement="";@State private var healthStatus="Not connected"
    var body:some View{Form{Section("Profile & Goal"){Picker("Goal",selection:Bindable(profile).goalRaw){Text("Cut").tag("cut");Text("Maintain / Recomp").tag("maintain");Text("Bulk").tag("bulk")};TextField("Calorie target",value:Bindable(profile).calorieTarget,format:.number).keyboardType(.numberPad);TextField("Protein target",value:Bindable(profile).proteinTarget,format:.number).keyboardType(.numberPad);TextField("Step target",value:Bindable(profile).stepTarget,format:.number).keyboardType(.numberPad);Picker("Units",selection:Bindable(profile).unitRaw){Text("Imperial").tag("imperial");Text("Metric").tag("metric")}}
        Section("Supplements"){ForEach(supplements){Text($0.name)}.onDelete{for i in $0{context.delete(supplements[i])}};HStack{TextField("Add supplement",text:$newSupplement);Button("Add"){guard !newSupplement.isEmpty else{return};context.insert(SupplementEntity(name:newSupplement,order:supplements.count));newSupplement=""}}}
        Section("Health & reminders"){Button("Connect / refresh Apple Health"){Task{do{try await HealthKitService().authorize();healthStatus="Access requested"}catch{healthStatus="Unavailable or denied"}}};Text(healthStatus).foregroundStyle(.secondary);Button("Enable weekly photo reminder"){Task{_ = try? await NotificationService.request();try? await NotificationService.scheduleWeeklyPhotos()}}}
        Section("Portfolio"){Toggle("Demo Mode",isOn:Binding(get:{profile.demoMode},set:{enabled in profile.demoMode=enabled;if enabled{DemoSeeder.seed(context:context,profile:profile)}}));Button("Reset Demo Data"){DemoSeeder.reset(context:context,profile:profile)}}
        Section("Privacy"){Text("Health data and progress photos remain on this device. Only food queries are sent to nutrition providers.").font(.footnote)}}.navigationTitle("Settings").toolbar{Button("Done"){try? context.save();dismiss()}} }
}

enum DemoSeeder { static func seed(context:ModelContext,profile:AppProfile){guard profile.demoMode else{return};let cal=Calendar.current;for offset in -35...0{let date=cal.date(byAdding:.day,value:offset,to:.now)!;context.insert(ActivityEntity(date:date,steps:Double(7000+abs(offset*379)%6000),activeCalories:Double(250+abs(offset*31)%350)));context.insert(WaterEntity(date:date,liters:Double(14+abs(offset)%8)/10));context.insert(WeightEntity(date:date,kilograms:70+Double(offset)*0.035));if offset % 2 == 0 {let w=WorkoutEntity(date:date,name:offset%4==0 ? "Lower Body A":"Upper Body",completed:true,exercises:[SessionExerciseEntity(name:"Hip Thrust",order:0,sets:[SetEntity(order:0,weightKG:60+Double(offset+35)/3,reps:10)])]);context.insert(w)};let food=FoodEntity(name:"Greek Yogurt Bowl",calories100:120,protein100:10,carbs100:14,fat100:3);context.insert(food);context.insert(FoodLogEntity(date:date,meal:.breakfast,food:food,grams:250))};try? context.save()};static func reset(context:ModelContext,profile:AppProfile){try? context.delete(model:ActivityEntity.self,where:#Predicate<ActivityEntity>{$0.steps >= 7000});profile.demoMode=true;seed(context:context,profile:profile)} }
