import SwiftUI
import SwiftData
import AVFoundation

struct WorkoutHome: View {
    @Query(sort: \WorkoutEntity.date, order: .reverse) private var sessions: [WorkoutEntity]; @Query private var templates: [TemplateEntity]
    @State private var add = false; @State private var builder = false
    var body: some View { ScrollView { VStack(spacing: 18) { EditorialTitle(eyebrow: "Training", title: "Move with intention"); Button { add = true } label: { Label("Add Workout", systemImage: "plus").frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).controlSize(.large); Button("Build weekly schedule") { builder = true }.buttonStyle(.bordered)
        if sessions.isEmpty { ContentUnavailableView("No sessions yet", systemImage: "dumbbell", description: Text("Start a strength or cardio workout.")) } else { ForEach(sessions.prefix(20)) { workout in NavigationLink { workout.isCardio ? AnyView(CardioEditor(workout: workout)) : AnyView(StrengthSessionView(workout: workout)) } label: { WellnessCard { HStack { VStack(alignment: .leading) { Text(workout.name).font(.headline); Text(workout.date.formatted(date: .abbreviated, time: .omitted)).foregroundStyle(.secondary) }; Spacer(); Image(systemName: workout.completed ? "checkmark.circle.fill" : "chevron.right").foregroundStyle(.sage) } } }.buttonStyle(.plain) } }
    }.padding(18) }.background(Color.cream.opacity(0.45)).sheet(isPresented: $add) { AddWorkoutView() }.sheet(isPresented: $builder) { NavigationStack { TemplateBuilderView() } }.navigationTitle("Workout").navigationBarTitleDisplayMode(.inline) }
}

struct AddWorkoutView: View {
    @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context; @Query private var templates: [TemplateEntity]
    @State private var cardio = false; @State private var selection = "Walking"
    var body: some View { NavigationStack { List { Section("Strength") { ForEach(templates) { template in Button(template.name) { let exercises = template.exerciseNames.enumerated().map { SessionExerciseEntity(name: $0.element, order: $0.offset, sets: (0..<template.defaultSets).map { SetEntity(order: $0) }) }; context.insert(WorkoutEntity(name: template.name, exercises: exercises)); try? context.save(); dismiss() } }; Button("Quick strength session") { context.insert(WorkoutEntity(name: "Strength", exercises: [])); try? context.save(); dismiss() } } Section("Cardio") { ForEach(["Walking", "Outdoor Walking", "Running", "Incline Treadmill", "Treadmill", "Cycling", "Stationary Bike", "Elliptical", "Stair Climber", "Swimming", "Rowing", "Hiking", "Other"], id: \.self) { name in Button(name) { context.insert(WorkoutEntity(name: name, isCardio: true)); try? context.save(); dismiss() } } } }.navigationTitle("Add Workout").toolbar { Button("Cancel") { dismiss() } } } }
}

struct StrengthSessionView: View {
    @Environment(\.modelContext) private var context; @Query private var library: [ExerciseEntity]; let workout: WorkoutEntity; @State private var addExercise = false
    var body: some View { List { ForEach(workout.exercises.sorted(by: { $0.order < $1.order })) { exercise in Section { NavigationLink { ExerciseDetail(name: exercise.name) } label: { Label("Form & tips", systemImage: "info.circle") }; ForEach(exercise.sets.sorted(by: { $0.order < $1.order })) { set in HStack { Text("Set \(set.order + 1)"); TextField("kg", value: Bindable(set).weightKG, format: .number).keyboardType(.decimalPad).textFieldStyle(.roundedBorder); TextField("reps", value: Bindable(set).reps, format: .number).keyboardType(.numberPad).textFieldStyle(.roundedBorder) } }.onDelete { indices in let ordered = exercise.sets.sorted(by: { $0.order < $1.order }); indices.forEach { context.delete(ordered[$0]) } }; Button("Add Set") { exercise.sets.append(SetEntity(order: exercise.sets.count)) } } header: { Text(exercise.name) } }
        Button("Add Exercise") { addExercise = true }; Button(workout.completed ? "Workout Completed" : "Finish Workout") { workout.completed = true; try? context.save() }.disabled(workout.completed).buttonStyle(.borderedProminent)
    }.navigationTitle(workout.name).sheet(isPresented: $addExercise) { NavigationStack { List(library) { item in Button(item.name) { workout.exercises.append(SessionExerciseEntity(name: item.name, order: workout.exercises.count, sets: [SetEntity(order: 0), SetEntity(order: 1), SetEntity(order: 2)])); addExercise = false } }.searchable(text: .constant("")) } } }
}

struct ExerciseDetail: View { @Query private var exercises: [ExerciseEntity]; let name: String; var body: some View { let exercise = exercises.first { $0.name == name }; ScrollView { VStack(alignment: .leading, spacing: 18) { RoundedRectangle(cornerRadius: 24).fill(Color.sage.opacity(0.15)).frame(height: 220).overlay { VStack { Image(systemName: "figure.strengthtraining.traditional").font(.system(size: 55)); Text("Demo media ready for licensed asset").font(.caption) } }; Text(exercise?.summary ?? "Custom exercise").font(.title3); Text("Form notes").font(.headline); ForEach((exercise?.tips ?? "Move with control").components(separatedBy: "\n"), id: \.self) { Label($0, systemImage: "checkmark") } }.padding() }.navigationTitle(name) } }

struct CardioEditor: View {
    @Environment(\.modelContext) private var context; let workout: WorkoutEntity
    var body: some View { Form { Section("Session") { LabeledContent("Duration (minutes)") { TextField("30", value: Bindable(workout).durationMinutes, format: .number).keyboardType(.decimalPad) }; LabeledContent("Distance (km)") { TextField("Optional", value: Bindable(workout).distanceKM, format: .number).keyboardType(.decimalPad) }; if workout.name.localizedCaseInsensitiveContains("incline") { LabeledContent("Incline %") { TextField("10", value: Bindable(workout).incline, format: .number).keyboardType(.decimalPad) } }; LabeledContent("Speed (km/h)") { TextField("Optional", value: Bindable(workout).speedKPH, format: .number).keyboardType(.decimalPad) }; LabeledContent("Calories") { TextField("Optional", value: Bindable(workout).calories, format: .number).keyboardType(.decimalPad) }; LabeledContent("Average heart rate") { TextField("Optional", value: Bindable(workout).averageHeartRate, format: .number).keyboardType(.decimalPad) }; TextField("Notes", text: Bindable(workout).notes, axis: .vertical) }; Button("Save & Complete") { workout.completed = true; try? context.save() }.buttonStyle(.borderedProminent) }.navigationTitle(workout.name) }
}

struct TemplateBuilderView: View {
    @Environment(\.modelContext) private var context; @Query private var templates: [TemplateEntity]; @Query private var exercises: [ExerciseEntity]; @State private var name = ""; @State private var weekday = 2
    var body: some View { List { Section("New template") { TextField("Template name", text: $name); Picker("Weekday", selection: $weekday) { ForEach(1...7, id: \.self) { Text(Calendar.current.weekdaySymbols[$0-1]).tag($0) } }; Button("Create") { guard !name.isEmpty else { return }; context.insert(TemplateEntity(name: name, weekday: weekday)); name = "" } } ForEach(templates) { template in Section { TextField("Name", text: Bindable(template).name); Picker("Scheduled day", selection: Bindable(template).weekday) { Text("Unscheduled").tag(0); ForEach(1...7, id: \.self) { Text(Calendar.current.weekdaySymbols[$0-1]).tag($0) } }; Stepper("Default sets: \(template.defaultSets)", value: Bindable(template).defaultSets, in: 1...10); NavigationLink("Exercises (\(template.exerciseNames.count))") { TemplateExercisesView(template: template, library: exercises) }; Button("Delete", role: .destructive) { context.delete(template) } } header: { Text(template.name) } } }.navigationTitle("Workout Schedule").toolbar { Button("Done") { try? context.save() } } }
}
struct TemplateExercisesView: View { let template: TemplateEntity; let library: [ExerciseEntity]; @State private var search = ""; var body: some View { List { Section("In template") { ForEach(template.exerciseNames, id: \.self) { Text($0) }.onDelete { template.exerciseNames.remove(atOffsets: $0) }.onMove { template.exerciseNames.move(fromOffsets: $0, toOffset: $1) } } Section("Add") { ForEach(library.filter { search.isEmpty || $0.name.localizedCaseInsensitiveContains(search) }) { exercise in Button { if !template.exerciseNames.contains(exercise.name) { template.exerciseNames.append(exercise.name) } } label: { Label(exercise.name, systemImage: "plus.circle") } } } }.searchable(text: $search).toolbar { EditButton() }.navigationTitle(template.name) } }

struct AddFoodView: View {
    @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context; @Query(sort: \FoodEntity.lastUsed, order: .reverse) private var cached: [FoodEntity]
    let date: Date; @State private var query = ""; @State private var results: [FoodSnapshot] = []; @State private var loading = false; @State private var error: String?; @State private var scanner = false; @State private var manual = false
    private let service = RemoteNutritionService(proxyURL: Bundle.main.object(forInfoDictionaryKey: "NutritionProxyURL").flatMap { URL(string: $0 as? String ?? "") })
    var body: some View { List { Section { HStack { TextField("Search foods", text: $query).submitLabel(.search).onSubmit { search() }; if loading { ProgressView() } }; Button { scanner = true } label: { Label("Scan barcode", systemImage: "barcode.viewfinder") }; Button { manual = true } label: { Label("Create food manually", systemImage: "square.and.pencil") }; if let error { Text(error).foregroundStyle(.secondary) } } Section("Recent") { ForEach(cached.prefix(8)) { food in NavigationLink(food.name) { FoodAmountView(food: food, date: date) } } } Section("Frequent") { ForEach(cached.sorted(by: { $0.useCount > $1.useCount }).prefix(8)) { food in NavigationLink(food.name) { FoodAmountView(food: food, date: date) } } } if !results.isEmpty { Section("Search results") { ForEach(results) { result in Button(result.name) { let entity = FoodEntity(name: result.name, brand: result.brand ?? "", barcode: result.barcode, calories100: result.nutrientsPer100Grams.calories, protein100: result.nutrientsPer100Grams.protein, carbs100: result.nutrientsPer100Grams.carbs, fat100: result.nutrientsPer100Grams.fat, servingGrams: result.servingGrams ?? 100); context.insert(entity); try? context.save(); results = []; query = "" } } } } }.navigationTitle("Add Food").sheet(isPresented: $scanner) { BarcodeScannerSheet { code in scanner = false; lookup(code) } }.sheet(isPresented: $manual) { ManualFoodView() }
    }
    private func search() { loading = true; error = nil; Task { do { results = try await service.search(query); if results.isEmpty { error = "No foods found. Create one manually." } } catch { self.error = "Food search is unavailable. Cached and manual foods still work." }; loading = false } }
    private func lookup(_ code: String) { loading = true; Task { do { if let food = try await service.barcode(code) { results = [food] } else { error = "Barcode not found. Create this food manually." } } catch { self.error = "Could not look up that barcode." }; loading = false } }
}

struct FoodAmountView: View { @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context; let food: FoodEntity; let date: Date; @State private var grams = 100.0; @State private var meal = Meal.breakfast; var body: some View { Form { Section(food.name) { TextField("Amount (g)", value: $grams, format: .number).keyboardType(.decimalPad); Picker("Meal", selection: $meal) { ForEach(Meal.allCases, id: \.self) { Text($0.rawValue.capitalized) } }; let scale = grams/100; LabeledContent("Calories", value: "\(Int(food.calories100*scale))"); LabeledContent("Protein", value: "\(Int(food.protein100*scale)) g") } Button("Add to \(meal.rawValue.capitalized)") { context.insert(FoodLogEntity(date: date, meal: meal, food: food, grams: grams)); food.useCount += 1; food.lastUsed = .now; try? context.save(); dismiss() }.buttonStyle(.borderedProminent) }.navigationTitle("Serving") } }
struct ManualFoodView: View { @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context; @State private var name=""; @State private var brand=""; @State private var calories=0.0; @State private var protein=0.0; @State private var carbs=0.0; @State private var fat=0.0; var body: some View { NavigationStack { Form { TextField("Name", text:$name); TextField("Brand (optional)", text:$brand); Section("Per 100 grams") { TextField("Calories", value:$calories, format:.number).keyboardType(.decimalPad); TextField("Protein", value:$protein, format:.number).keyboardType(.decimalPad); TextField("Carbs", value:$carbs, format:.number).keyboardType(.decimalPad); TextField("Fat", value:$fat, format:.number).keyboardType(.decimalPad) } } .navigationTitle("Custom Food").toolbar { Button("Save") { guard !name.isEmpty else{return}; context.insert(FoodEntity(name:name, brand:brand, calories100:calories, protein100:protein, carbs100:carbs, fat100:fat)); try? context.save(); dismiss() } } } } }

struct BarcodeScannerSheet: UIViewControllerRepresentable { let completion: (String)->Void; func makeUIViewController(context: Context) -> ScannerController { let c=ScannerController(); c.completion=completion; return c }; func updateUIViewController(_ uiViewController: ScannerController, context: Context) {} }
final class ScannerController: UIViewController, AVCaptureMetadataOutputObjectsDelegate { var completion: ((String)->Void)?; private let session=AVCaptureSession(); override func viewDidLoad(){ super.viewDidLoad(); view.backgroundColor=.black; guard let camera=AVCaptureDevice.default(for:.video), let input=try? AVCaptureDeviceInput(device:camera), session.canAddInput(input) else{return}; session.addInput(input); let output=AVCaptureMetadataOutput(); guard session.canAddOutput(output) else{return}; session.addOutput(output); output.setMetadataObjectsDelegate(self, queue:.main); output.metadataObjectTypes=[.ean8,.ean13,.upce]; let layer=AVCaptureVideoPreviewLayer(session:session); layer.frame=view.bounds; layer.videoGravity=.resizeAspectFill; view.layer.addSublayer(layer); DispatchQueue.global(qos:.userInitiated).async { self.session.startRunning() } }; func metadataOutput(_ output: AVCaptureMetadataOutput, didOutput metadataObjects:[AVMetadataObject], from connection:AVCaptureConnection){ guard let value=(metadataObjects.first as? AVMetadataMachineReadableCodeObject)?.stringValue else{return}; session.stopRunning(); completion?(value) } }
